#!/bin/bash

JUJU_ENV=''
ITERATES=1
PORT=80
HOST=''

print_usage(){
  printf "usage:
    [-i count]
    [-e juju env to find haproxy]
    [-p haproxy port]
    [-h host - ignore find haproxy]
    \n"
}

while getopts 'e:i:p:h:' flag; do
    case "${flag}" in
        e)  JUJU_ENV=$OPTARG ;;
        i)  ITERATES=$OPTARG ;;
        p)  PORT="$OPTARG" ;;
        h)  HOST=$OPTARG ;;
        *)  print_usage
            exit 1
            ;;
    esac
done

if [ -z "$HOST" ]; then
    if [ -z "$JUJU_ENV" ]; then   
        print_usage
        exit 1
    fi
    HAPROXY_HOST=`juju status -e $JUJU_ENV haproxy | grep public-address | sed 's/.*: //g'`
    HOST="$HAPROXY_HOST:$PORT"
fi

URL=http://$HOST/

echo "Run $ITERATES iterate(s) for $URL"


ab -n 1000000 -c $ITERATES -r $URL
#-T application/x-www-form-urlencoded -p ab.data $URL


