- hosts: all
  vars:
    APP_NAME: monitor-server
    WORK_DIR: "/opt/{{ APP_NAME }}"
    CONFIG_PATH: "{{ WORK_DIR }}/{{ APP_NAME }}.conf"
    APP_SCRIPT_CONFIG: vars/app_vars.yaml
    APP_BIN: "{{ WORK_DIR }}/monitor-server"
    JUJU_TOOL_CONFIG_PATH: "{{ WORK_DIR }}/.jujuapi.yaml"
  vars_files:
    - "{{ APP_SCRIPT_CONFIG }}"
  handlers:
    - name: dump config
      template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: './templates/app.conf', dest: "{{ CONFIG_PATH }}" }
        - { src: './templates/app_vars.yaml', dest: "{{ APP_SCRIPT_CONFIG }}" }
        - { src: './templates/juju.yaml', dest: "{{ JUJU_TOOL_CONFIG_PATH }}" }

    - name: restart
      service: name={{ APP_NAME }} state=restarted

  tasks:
    - name: install monitor server
      include: install.yaml
      tags: install 

    - name: config changed
      include: config-changed.yaml
      tags: config-changed

    - name: juju api relation changed
      include: api-server-relation-changed.yaml
      tags: api-server-relation-changed

    - name: redis relation changed
      include: redis-relation-changed.yaml
      tags: redis-relation-changed

    - name: mesos master relation changed 
      include: mesos-master-changed.yaml
      tags: mesos-master-relation-changed

    - name: monitor server relation changed
      include: monitor-server-changed.yaml
      tags: monitor-server-relation-changed

    - name: essearch relation changed
      include: essearch-relation-changed.yaml
      tags: essearch-relation-changed

    - name: start app
      service: name={{ APP_NAME }} state=started
      tags: start

    - name: stop app
      service: name={{ APP_NAME }} state=stopped
      tags: stop
