options:
  JUJU_API_HOST:
    type: string
    description: "juju api host. It will be ignored if relation between juju-gui and monitor-server is created"
  JUJU_API_PASSWORD:
    type: string
    default: "pswd"
    description: "Admin password to api"
  CHECK_PERIOD:
    type: int
    default: 300
    description: "Avg period in seconds"
  PORT:
    type: int
    default: 8090
    description: "Web server port"
  JUJU_DEPLOY_DELAY:
    type: int
    default: 10
    description: "Juju deploy delay"
  MESOS_DEPLOY_DELAY:
    type: int
    default: 1
    description: "Mesos service deploy delay"
  JUJU_SCALE_UP:
    type: int
    default: 70
    description: "Juju scale up limit"
  JUJU_SCALE_DOWN:
    type: int
    default: 30
    description: "Juju scale down limit"
  MESOS_SCALE_UP:
    type: int
    default: 60
    description: "Mesos scale up limit"
  MESOS_SCALE_DOWN:
    type: int
    default: 10
    description: "Mesos scale down limit"
  ESSEARCH_TIMING:
    type: int
    default: 10
    description: "Send data to essearch period (in seconds)"
  IGNORE_LIST:
    type: string
    default: ""
    description: "app ignore list(comma separated)"
