options:
  CHECK_PERIOD:
    type: int
    default: 5
    description: "Avg period in minutes"
  PORT:
    type: int
    default: 8090
    description: "Web server port"
  JUJU_API_PASSWORD:
    type: string
    default: "pswd"
    description: "Admin password to api"
  JUJU_DEPLOY_DELAY:
    type: int
    default: 10
    description: "Juju deploy delay"
  MESOS_DEPLOY_DELAY:
    type: int
    default: 1
    description: "Mesos service deploy delay"
  SCALE_UP:
    type: int
    default: 70
    description: "Scale up limit"
  SCALE_DOWN:
    type: int
    default: 30
    description: "Scale down limit"
