#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

. hooks/common.sh

. $CONFIG_PATH

RESTCOMM_USER=`config-get RESTCOMM_USER`
RESTCOMM_PASSWORD=`config-get RESTCOMM_PASSWORD`

render_config

restart_me
