#!/bin/bash
source hooks/common.sh

. $CONFIG_PATH 

RESTCOMM_SERVICE_NEW=`relation-get hostname`:`relation-get port`

if [ $RESTCOMM_SERVICE != $RESTCOMM_SERVICE_NEW ]; then
    RESTCOMM_SERVICE=$RESTCOMM_SERVICE_NEW
    render_config
    restart_me
fi

