#!/bin/bash

source hooks/common.sh

. $CONFIG_PATH 

PRIVATE_ADDRESS=$(unit-get private-address)
#relation-set "hostname=${PRIVATE_ADDRESS}"
#relation-set "port=$APP_PORT"
#relation-set "service_name=tads2015_calls_consumer"

echo "services=[{'service_name': '${APP_NAME}_${APP_PORT}'
'service_host': '0.0.0.0'
'service_port': '${APP_PORT}'
'service_options': ['mode http', 'balance roundrobin', 'option forwardfor']
'servers': [['${APP_NAME}_${APP_PORT}', '${PRIVATE_ADDRESS}', '${APP_PORT}', 'check']]
}]"

relation-set "services=[{'service_name': '${APP_NAME}_${APP_PORT}',
'service_host': '0.0.0.0',
'service_port': '${APP_PORT}',
'service_options': ['mode http', 'balance roundrobin', 'option forwardfor'],
'servers': [['${APP_NAME}_${APP_PORT}', '${PRIVATE_ADDRESS}', '${APP_PORT}', 'check']]
}]"


EXTERNAL_IP=`relation-get public-address`

render_config
restart_me

