
---
- name: get juju api host
  shell: echo $JUJU_REMOTE_UNIT | sed 's/\/.*//g'
  register: local_machine_host

- set_fact:
    global:
      JUJU_SERVICE_ID: "{{ local_machine_host.stdout }}"
  changed_when: true
  notify: 
    - dump config
    - restart