#!/bin/bash

set -ex

if [ -z `relation-list` ]
then
	juju-log "No mesos-master information sent yet. Silently exiting"
	if $(service mesos-slave status|grep 'mesos-slave start/running' | wc -l)
	then
		sudo service mesos-slave stop
	fi
	status-set waiting "Waiting for active mesos-master connection"
else
	sudo service mesos-slave restart

	if [ `config-get install_docker` = "True" ]
	then
		sudo service docker restart
	fi

	status-set active
fi

if $(service mesos-master status|grep 'mesos-master start/running' | wc -l)
then
	sudo service mesos-master stop
fi

if $(service zookeeper status|grep 'zookeeper start/running' | wc -l)
then
	sudo service zookeeper stop
fi