#!/bin/bash

. hooks/common.sh

. $CONFIG_PATH

#REDIS_SERVICE_HOST=`relation-get hostname`
#REDIS_SERVICE_PORT=`relation-get port`

#REDIS_SERVICE_HOST=`relation-get private-address`
#REDIS_SERVICE_PORT=6379
REDIS_HOST=`relation-get hostname`:`relation-get port`

render_config
restart_me

