#!/bin/bash

. hooks/common.sh

. ${CONFIG_PATH}

EXTERNAL_IP=`relation-get public-address`

render_config
render_init

# recreate rc, pods
kubectl_recreate

# update haproxy 
. hooks/haproxy.sh

HAPROXY_CONFIG=$(generate_haproxy_config main)

echo "haproxy config = ${HAPROXY_CONFIG}"

relation-set "$HAPROXY_CONFIG"
