#!/bin/bash
set -x

juju-log  "cscf-relation-changed"

#get cscf-uri
cscf_uri=`relation-get cscf-uri`
[ -n "$cscf_uri" ] || exit 0

# Stop Restcomm to configure outbound proxy
hooks/stop

juju-log  "Cscf relation changed cscf_uri: $cscf_uri"
juju-log "Removing sip: from the $cscf_uri URI"
cscf_host_port=${cscf_uri#sip\:}
juju-log "Reconfiguring RestComm to use the $cscf_host_port as an outbound Proxy"

RESTCOMM_HOME=/opt/restcomm
outbound_proxy=$cscf_host_port
restcomm_config="$RESTCOMM_HOME/standalone/deployments/restcomm.war/WEB-INF/conf/restcomm.xml"
sed -e "s|<outbound-proxy-uri>.*<\/outbound-proxy-uri>|<outbound-proxy-uri>$outbound_proxy<\/outbound-proxy-uri>|" \
$restcomm_config > $restcomm_config.bak
mv -f $restcomm_config.bak $restcomm_config

juju-log "Reconfigured RestComm to use the $cscf_host_port Proxy"

hooks/start

juju-log  "cscf-relation-changed completed"

