#!/bin/sh
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.

set -x

# Try to use metadata for a public hostname; but fall back to local processing
h=$(unit-get private-address)

relation-set port="8080" hostname="$h"

