
---
- name: map config to var
  set_fact:
#reload config vars to our vars
    RESTCOMM_USER_VAR: "{{ RESTCOMM_USER }}"
    RESTCOMM_PASSWORD_VAR: "{{ RESTCOMM_PASSWORD }}"

  changed_when: true
  notify: 
    - dump config
    - restart
