#!/bin/bash

source hooks/common.sh

. $CONFIG_PATH 

PRIVATE_ADDRESS=$(unit-get private-address)
EXTERNAL_IP_NEW=`relation-get public-address`

if [ $EXTERNAL_IP != $EXTERNAL_IP_NEW ]; then
    EXTERNAL_IP=$EXTERNAL_IP_NEW
    render_config
    restart_me

    sleep 10
fi

SERVICES=`get_ha_service`

relation-set "$SERVICES"
