#!/bin/bash
source hooks/common.sh

. $CONFIG_PATH 

RECORDER_HOST_NEW=`relation-get hostname`:`relation-get port`

if [ "$RECORDER_HOST" != $RECORDER_HOST_NEW ]; then
    RECORDER_HOST=$RECORDER_HOST_NEW
    render_config
    restart_me
fi

