#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

juju-log "Installing mesos-master on $JUJU_UNIT_NAME"
status-set maintenance "Fetching and installing Mesos"

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update
sudo apt-get -y install mesos marathon=0.10.1-1.0.416.ubuntu1404 wget git-core make

# Install docker
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu

# Install mesos-dns
juju-log "Installing mesos-dns on $JUJU_UNIT_NAME"
wget -O mesos-dns https://github.com/mesosphere/mesos-dns/releases/download/v0.5.1/mesos-dns-v0.5.1-linux-amd64
chmod +x mesos-dns
sudo mkdir -p /usr/local/mesos-dns
sudo mv mesos-dns /usr/local/mesos-dns

cat > /etc/init/mesos-dns.conf <<EOL
description "mesos dns"

start on stopped rc RUNLEVEL=[2345]
respawn

exec /usr/local/mesos-dns/mesos-dns -config=/usr/local/mesos-dns/config.json
EOL

sudo cp /etc/resolvconf/resolv.conf.d/head /etc/resolvconf/resolv.conf.d/head.backup

UNIT_PRIVATE_ADDRESS=`unit-get private-address`
HOSTNAME=`hostname`
echo "nameserver $UNIT_PRIVATE_ADDRESS" >> /etc/resolvconf/resolv.conf.d/head
echo "$UNIT_PRIVATE_ADDRESS $HOSTNAME" >> /etc/hosts

resolvconf -u

sudo sh -c "echo `config-get zookeeper` > /etc/mesos/zk"
sudo sh -c "echo `config-get quorum` > /etc/mesos-master/quorum"
