#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

juju-log "Installing mesos-master on $JUJU_UNIT_NAME"
status-set maintenance "Fetching and installing Mesos"

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update
sudo apt-get -y install mesos marathon wget git-core make

# Install docker
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu

# Install mesos-dns
juju-log "Installing mesos-dns on $JUJU_UNIT_NAME"

wget https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz
tar xzf go*
sudo mv go /usr/local/.
export PATH=$PATH:/usr/local/go/bin
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/ubuntu/go
go get github.com/tools/godep
export PATH=$PATH:$GOPATH/bin

go get github.com/mesosphere/mesos-dns
cd $GOPATH/src/github.com/mesosphere/mesos-dns

#make all

godep go build ./...
godep go install

sudo mkdir /usr/local/mesos-dns
sudo mv $GOPATH/bin/mesos-dns /usr/local/mesos-dns

cat > /etc/init/mesos-dns.conf <<EOL
description "mesos dns"

start on stopped rc RUNLEVEL=[2345]
respawn

exec /usr/local/mesos-dns/mesos-dns -config=/usr/local/mesos-dns/config.json
EOL

sudo cp /etc/resolv.conf /etc/resolv.conf.backup

sudo sh -c "echo `config-get zookeeper` > /etc/mesos/zk"
sudo sh -c "echo `config-get quorum` > /etc/mesos-master/quorum"
