#!/bin/bash

set -ex

if $(service zookeeper status|grep 'zookeeper start/running' | wc -l)
then
	sudo service zookeeper stop
fi
if $(service mesos-master status|grep 'mesos-master start/running' | wc -l)
then
	sudo service mesos-master stop
fi
if $(service marathon status|grep 'marathon start/running' | wc -l)
then
	sudo service marathon stop
fi

if $(service mesos-slave status|grep 'mesos-slave start/running' | wc -l)
then
	sudo service mesos-slave stop
fi

if $(service docker status|grep 'docker start/running' | wc -l)
then
	sudo service docker stop
fi

if $(service mesos-dns status|grep 'mesos-dns start/running' | wc -l)
then
	sudo service mesos-dns stop
fi

status-set maintenance "service stopped"