
---
- name: get recorder host
  shell: relation-get hostname
  register: local_host

- name: get recorder port
  shell: relation-get port
  register: local_port

- set_fact:
    RECORDER_HOST_VAR: "{{ local_host.stdout }}:{{ local_port.stdout }}"
  changed_when: true
  when: local_host.stdout != "" and (local_host.stdout + ":" + local_port.stdout) != RECORDER_HOST_VAR
  notify: 
    - dump config
    - restart