
---
- name: add cron job
  cron:
    name: "haproxy_{{ APP_NAME }}"
    job: "juju-run {{ UNIT_NAME_VAR }} actions/mesos-app-changed  >> /var/log/{{ APP_NAME }}_cron.log 2>&1"

- name: start app
  command: /bin/true
  notify:
    - restart
