tads2015-demo:
  services:
    haproxy:
      options:
        services: "[]"
    telscale-restcomm:
      options:
        voicerss_key: "29b2d893df9f454abbfae94df6cff95b"   
        init_password: "42d8aa7cde9c78c4757862d84620c335" 
