#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

. hooks/common.sh
. $CONFIG_PATH

CONFIG_JUJU_API_HOST=`config-get JUJU_API_HOST`
JUJU_API_PASSWORD=`config-get JUJU_API_PASSWORD`
CHECK_PERIOD=`config-get CHECK_PERIOD`
PORT=`config-get PORT`
JUJU_DEPLOY_DELAY=`config-get JUJU_DEPLOY_DELAY`
MESOS_DEPLOY_DELAY=`config-get MESOS_DEPLOY_DELAY`
SCALE_UP=`config-get SCALE_UP`
SCALE_DOWN=`config-get SCALE_DOWN`

render_config
render_juju_tool_config

restart_me
